"""Add Story.section column

Revision ID: 4907015106a4
Revises: 05449f4f690b
Create Date: 2025-10-22 12:02:35.636095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4907015106a4'
down_revision = '05449f4f690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('story', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
